# Generated by Django 5.1.2 on 2024-10-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_category_options_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_successful",
        ),
    ]
