# Generated by Django 5.1.2 on 2024-10-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_rename_user_payment_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="username",
            new_name="user",
        ),
    ]
